### ISSUE TITLE
Дописать бекенд и сделать миграцию на fastify

### ISSUE THREAD

**Issue by MindBreakerGM** [MindBreakerGM/BookList#58]
![изображение](https://user-images.githubusercontent.com/58743402/176886806-2d3e7790-578e-4c77-bebc-aa1bcfe98659.png)
Прирост более чем в 4 раза запросов в секунду.

**Comment by ResponseGood** [comment]
https://www.fastify.io/docs/latest/Guides/Getting-Started/
